version: "3.9"

# This version uses a local build of the image
services:
  documentation:
    build: .
    container_name: ai-code-annotator
    
    volumes:
      # Path to the project to be documented
      - /Users/xxx:/app/project
      # Specific mount for the tasks_and_prompts.yaml (only specify if you want to use specific tasks, file filters, or custom tasks)
      # - /Users/XXXX/tasks_and_prompts.yaml:/app/tasks_and_prompts.yaml
    environment:
      - BASE_DIR=/app/project
      # Choose a task suitable for you (see tasks_and_prompts.yaml)
      - TASKS=documentation
      # Azure OpenAI API Key
      - AZURE_OPENAI_API_KEY=xxx

    restart: "no"

